name: pr

on: pull_request

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # pin@v3.0
        with:
          go-version: "1.19"

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@c675eb70db3aa26b496bc4e64da320480338d41b # pin#v3
        with:
          version: v1.51.2

  setup:
    uses: janus-idp/.github/.github/workflows/setup.yaml@main
    with:
      default_tag_version: "latest"
      build_platforms: "linux/amd64,linux/arm64"

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    strategy:
      matrix:
        platform: ${{ fromJson(needs.setup.outputs.dist_matrix) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - name: Build images
        uses: janus-idp/.github/.github/actions/build-and-push@main
        with:
          platform: ${{ matrix.platform }}
          image_tag: ${{ needs.setup.outputs.image_tag }}
          push: false

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # pin@v3.0
        with:
          go-version: "1.19"

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3

      - name: Test
        run: go test -v ./...
